# Generated by Django 2.0.9 on 2018-12-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_cliente', models.CharField(max_length=50)),
                ('Rut', models.CharField(max_length=10)),
                ('Direccion', models.TextField()),
                ('Ciudad', models.CharField(max_length=50)),
                ('Comuna', models.CharField(max_length=50)),
                ('Telefono', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Hora_inicio', models.TimeField()),
                ('Hora_fin', models.TimeField()),
                ('Codigo_ascensor', models.CharField(max_length=50)),
                ('Fallas', models.TextField()),
                ('Reparaciones', models.TextField()),
                ('Piezas_cambiadas', models.TextField()),
                ('Nombre_cliente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Tecnico', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Contraseña', models.CharField(max_length=50)),
            ],
        ),
    ]
