# Generated by Django 2.0.9 on 2018-12-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='Modelo_ascensor',
            field=models.CharField(default=321321, max_length=50),
            preserve_default=False,
        ),
    ]
