# Generated by Django 2.0.9 on 2018-12-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0002_orden_modelo_ascensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='Fecha',
            field=models.DateTimeField(),
        ),
    ]
